services:
  - type: web
    name: sk-presidencypublicschool
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: IMGBB_API_KEY
        sync: false
