if(!sessionStorage.getItem('skpps_auth')||sessionStorage.getItem('skpps_role')!=='mgmt'){location.href='../staff-login.html'}
document.getElementById('uname').textContent=' - '+(sessionStorage.getItem('skpps_name')||'Admin');

function gs(){try{return JSON.parse(localStorage.getItem('skpps_students')||'[]')}catch(e){return[]}}
function ss(a){localStorage.setItem('skpps_students',JSON.stringify(a))}
function gt(){try{return JSON.parse(localStorage.getItem('skpps_teachers')||'[]')}catch(e){return[]}}
function st(a){localStorage.setItem('skpps_teachers',JSON.stringify(a))}

if(gs().length===0){ss([{sid:'SKPPS2024001',roll:12,name:'Mohd Haziq',father:'Mohd Work',dob:'2016-03-15',cls:'IV',sec:'A',house:'Earth',blood:'B+',phone:'8601735757',added:new Date().toISOString()},{sid:'SKPPS2024002',roll:5,name:'Deepanshi Gupta',father:'Rajesh Gupta',dob:'2014-08-20',cls:'VIII',sec:'B',house:'Water',blood:'O+',phone:'8601738180',added:new Date().toISOString()}])}
if(gt().length===0){st([{user:'teacher1',pass:'teacher123',name:'Mrs. Sharma'},{user:'teacher2',pass:'teacher123',name:'Mr. Verma'},{user:'teacher3',pass:'teacher123',name:'Mrs. Singh'}])}

var students=gs(),teachers=gt(),curTab='scan';
function logout(){sessionStorage.clear();location.href='../staff-login.html'}
function showTab(t){curTab=t;render()}

function render(){
  var s=students,t=teachers,h='';
  h+='<div class="stats"><div class="stat"><div class="v">'+s.length+'</div><div class="l">Students</div></div><div class="stat"><div class="v">'+t.length+'</div><div class="l">Teachers</div></div><div class="stat"><div class="v">'+new Set(s.map(function(x){return x.cls})).size+'</div><div class="l">Classes</div></div></div>';
  h+='<div class="tabs-nav"><button class="'+(curTab==='scan'?'active':'')+'" onclick="curTab=\'scan\';render()">Scan ID Card</button><button class="'+(curTab==='bulk'?'active':'')+'" onclick="curTab=\'bulk\';render()">Bulk Import</button><button class="'+(curTab==='teacher'?'active':'')+'" onclick="curTab=\'teacher\';render()">Teachers</button><button class="'+(curTab==='all'?'active':'')+'" onclick="curTab=\'all\';render()">All Students</button></div>';
  if(curTab==='scan')h+=rScan();else if(curTab==='bulk')h+=rBulk();else if(curTab==='teacher')h+=rTeacher(t);else h+=rAll(s);
  document.getElementById('mc').innerHTML=h;if(curTab==='scan')setTimeout(startCam,200);
}

function rScan(){return '<div class="card"><div class="ch">Scan ID Card &amp; Add Student</div><div class="cb"><p style="font-size:12px;color:var(--g600);margin-bottom:10px">Camera se ID card scan karein. Text auto-extract hoga.</p><div id="camBox"><video id="camVid" autoplay playsinline></video><div class="ol"></div></div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn btn-b" onclick="scanCard()" id="btnScan">Scan &amp; Extract</button><button class="btn btn-o" onclick="stopCam()">Stop Camera</button></div><div id="scanOut" style="margin-top:12px"></div></div></div>'}
function rBulk(){return '<div class="card"><div class="ch">Bulk Import</div><div class="cb"><p style="font-size:11px;color:var(--g600);margin-bottom:8px">CSV format: ID,Name,Class,Section,Roll,DOB,Father,Mother,Phone,Gender,House</p><textarea id="csvData" style="width:100%;height:120px;border:1.5px solid var(--g300);border-radius:var(--rs);padding:10px;font-family:monospace;font-size:11px" placeholder="SKPPS2024003,Amit,V,A,8,2017-05-10,Ram,Sita,9876543210,Male,Earth"></textarea><button class="btn btn-b mt1" onclick="importCSV()">Import</button><div id="csvMsg" class="mt1"></div></div></div>'}
function rTeacher(t){var rows='';for(var i=0;i<t.length;i++)rows+='<tr><td>'+t[i].name+'</td><td>'+t[i].user+'</td><td><span class="badge-sm bg">Active</span></td></tr>';return '<div class="card"><div class="ch">Add Teacher</div><div class="cb"><form onsubmit="return addTeacher(event)"><div class="r2"><div class="fg"><label>Full Name</label><input id="tn" required></div><div class="fg"><label>Username</label><input id="tu" required></div></div><div class="r2"><div class="fg"><label>Password</label><input type="password" id="tpw" required minlength="4"></div><div class="fg"><label>Email</label><input type="email" id="te"></div></div><button type="submit" class="btn btn-b mt1">Add Teacher</button></form><h4 style="font-size:12px;color:var(--g600);margin-top:14px;margin-bottom:6px">Teachers:</h4><div class="tw"><table class="dt"><tr><th>Name</th><th>Username</th><th>Status</th></tr>'+rows+'</table></div></div></div>'}
function rAll(s){var rows='';for(var i=0;i<s.length;i++){var hc=s[i].house;rows+='<tr><td>'+s[i].sid+'</td><td><strong>'+s[i].name+'</strong></td><td>'+s[i].cls+'</td><td>'+s[i].sec+'</td><td>'+s[i].roll+'</td><td><span class="badge-sm '+(hc==='Earth'?'bg':hc==='Fire'?'br':hc==='Water'?'bb':'by')+'">'+hc+'</span></td><td>'+s[i].phone+'</td><td style="font-size:10px">'+s[i].dob+'</td></tr>'}return '<div class="card"><div class="ch">All Students ('+s.length+')</div><div class="cb"><input style="width:100%;padding:8px 10px;border:1.5px solid var(--g300);border-radius:var(--rs);font-size:12px;font-family:var(--f);margin-bottom:10px" placeholder="Search..." oninput="filterStudents(this.value)"><div class="tw"><table class="dt" id="stbl"><tr><th>ID</th><th>Name</th><th>Class</th><th>Sec</th><th>Roll</th><th>House</th><th>Phone</th><th>DOB</th></tr>'+rows+'</table></div></div></div>'}
function filterStudents(q){var r=document.querySelectorAll('#stbl tr');for(var i=1;i<r.length;i++)r[i].style.display=r[i].textContent.toLowerCase().includes(q.toLowerCase())?'':'none'}
function addTeacher(e){e.preventDefault();var n=document.getElementById('tn').value.trim(),u=document.getElementById('tu').value.trim(),p=document.getElementById('tpw').value.trim(),em=document.getElementById('te').value.trim();teachers.push({user:u,pass:p,name:n,email:em});st(teachers);alert('Teacher added!');render();return false}
function importCSV(){var t=document.getElementById('csvData').value.trim();if(!t)return;var l=t.split('\n'),a=0,s=0;for(var i=0;i<l.length;i++){var c=l[i].split(',').map(function(x){return x.trim()});if(c.length<6){s++;continue}var sid=c[0]||('SKPPS'+Date.now().toString(36).toUpperCase()),name=c[1],cls=c[2],sec=c[3]||'A',roll=parseInt(c[4])||0,dob=c[5]||'2000-01-01',father=c[6]||'',mother=c[7]||'',phone=c[8]||'',gender=c[9]||'Male',house=c[10]||'Earth';if(!name||!cls){s++;continue}students.push({sid:sid,roll:roll,name:name,father:father,mother:mother,dob:dob,gender:gender,cls:cls,sec:sec,house:house,phone:phone,added:new Date().toISOString()});a++}ss(students);document.getElementById('csvMsg').innerHTML='<div class="alert aok">Imported: '+a+'. Skipped: '+s+'</div>';render()}

var camStream=null;
function startCam(){var v=document.getElementById('camVid');if(!v)return;navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1920}}}).then(function(s){camStream=s;v.srcObject=s}).catch(function(){document.getElementById('camBox').innerHTML='<div style="color:white;text-align:center;padding:25px;font-size:12px">Camera unavailable</div>'})}
function stopCam(){if(camStream){camStream.getTracks().forEach(function(t){t.stop()});camStream=null}}

async function scanCard(){var btn=document.getElementById('btnScan'),v=document.getElementById('camVid'),c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);btn.disabled=true;btn.textContent='Scanning...';
try{var w=await Tesseract.createWorker('eng'),d=await w.recognize(c);await w.terminate();var txt=d.data.text.replace(/[^a-zA-Z0-9\s\/\-\.\,\:\@]/g,' ').replace(/\s+/g,' '),lines=txt.split('\n').map(function(l){return l.trim()}).filter(Boolean),ex={name:'',cls:'',roll:'',sid:'',father:'',phone:'',dob:'',blood:''};
for(var i=0;i<lines.length;i++){var l=lines[i],lo=l.toLowerCase();if(!ex.name&&(lo.includes('name')||l.match(/^[A-Z][a-z]+ [A-Z]/)))ex.name=l.replace(/name[: ]*/i,'').trim();else if(!ex.cls&&lo.includes('class'))ex.cls=l.replace(/class[: ]*/i,'').trim();else if(!ex.cls&&l.match(/^(Nursery|LKG|UKG|[IVX]+)$/i))ex.cls=l;else if(!ex.roll&&(lo.includes('roll')||lo.includes('rno')))ex.roll=l.replace(/(roll|rno)[: .]*/i,'').trim();else if(!ex.roll&&l.match(/^\d{1,3}$/))ex.roll=l;else if(!ex.sid&&(lo.includes('id')||lo.includes('adm')))ex.sid=l.replace(/(id|adm|admission)[: .]*/i,'').trim();else if(!ex.father&&lo.includes('father'))ex.father=l.replace(/father[: ]*/i,'').trim();else if(!ex.phone&&l.match(/^\d{10}$/))ex.phone=l;else if(!ex.dob&&(lo.includes('dob')||lo.includes('birth')))ex.dob=l.replace(/(dob|birth|date)[: .]*/i,'').trim();else if(!ex.blood&&lo.includes('blood'))ex.blood=l.replace(/(blood|bg|group)[: .]*/i,'').trim()}
document.getElementById('scanOut').innerHTML='<div style="background:var(--g50);padding:12px;border-radius:var(--rs)"><h4 style="font-size:12px;margin-bottom:8px">Scanned - Verify &amp; Save</h4><form onsubmit="return saveScanned(event)"><div class="r2"><div class="fg"><label>Student ID</label><input name="sid" value="'+ex.sid+'"></div><div class="fg"><label>Full Name *</label><input name="name" value="'+ex.name+'" required></div></div><div class="r2"><div class="fg"><label>Class *</label><input name="cls" value="'+ex.cls+'" required></div><div class="fg"><label>Section</label><select name="sec"><option>A</option><option>B</option><option>C</option></select></div></div><div class="r2"><div class="fg"><label>Roll No</label><input name="roll" value="'+ex.roll+'"></div><div class="fg"><label>DOB</label><input name="dob" type="date" value="'+ex.dob+'"></div></div><div class="r2"><div class="fg"><label>Father</label><input name="father" value="'+ex.father+'"></div><div class="fg"><label>Phone</label><input name="phone" value="'+ex.phone+'"></div></div><div class="r2"><div class="fg"><label>Blood Group</label><input name="blood" value="'+ex.blood+'"></div><div class="fg"><label>House</label><select name="house"><option>Earth</option><option>Fire</option><option>Water</option><option>Air</option></select></div></div><button type="submit" class="btn btn-b mt1">Save Student</button></form></div>'}catch(e){document.getElementById('scanOut').innerHTML='<div class="alert aerr">OCR failed. Try again.</div>'}btn.disabled=false;btn.textContent='Scan & Extract'}
function saveScanned(e){e.preventDefault();var f=e.target,sid=f.sid.value||('SKPPS'+Date.now().toString(36).toUpperCase()),name=f.name.value,cls=f.cls.value,sec=f.sec.value,roll=parseInt(f.roll.value)||0,dob=f.dob.value||'2000-01-01',father=f.father.value,phone=f.phone.value,blood=f.blood.value,house=f.house.value;students.push({sid:sid,roll:roll,name:name,father:father,mother:'',dob:dob,cls:cls,sec:sec,house:house,blood:blood,phone:phone,added:new Date().toISOString()});ss(students);alert('Student '+name+' saved!');render();return false}
render();
